[package]
name = "aoc-2020"
version = "0.1.0"
edition = "2018"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
bstr = "0.2.14"
bstr_parse = "0.1.0"
itertools = "0.9.0"
lalrpop-util = "0.19.0"
memchr = "2.3.4"
rayon = "1.5.0"
regex = "1.4.2"