[package]
name = "day-02"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "day-02-part-01"
path = "src/part-01.rs"

[[bin]]
name = "day-02-part-02"
path = "src/part-02.rs"

[dependencies]
memchr = "2.3.4"
regex = "1.4.2"
